os:
  - linux
  - osx
language: elixir
elixir:
  - 1.1.1
otp_release:
  - 17.5
  - 18.0
  - 18.1
sudo: false
after_script:
  - mix deps.get --only docs
  - mix compile
  - MIX_ENV=docs mix inch.report
